<style>
   .container-message 
   {
      width: 80rem;
      height: 80vh;
      border: 1px solid red;
      margin: 1rem 0;
    }
    .feild
    {
         width: 80rem;
         height: auto;
         margin: 0;
    }
    
    .send-message{
         width: 75rem;
         height: 2rem;
    }
    
    .btn-send{
        width: 5rem;
        height: 2rem;
        padding : 0 auto;
    }

</style>

<section class="container-message">
            <!--Dans cette Section, viendrons se placer les user_message-->
</section>

<div class="field">
            
           <input type="text" class="send-message" name="send-message" placeholder="Send a message...">
           <button class="btn-send">Send</button>
</div>

