<form  method="POST">
    <fieldset>
        <legend>Create Category</legend>
        
        <div class="field">
            <label for="create-category">Category name : </label>
            <div class="create-category"><input type="text" id="create-category" name="create-category"></div>
        </div>
        
        <div class="field">
            <label for="desc-category">Description : </label>
            <div class="desc-category"><input type="text" id="desc-category" name="desc-category"></div>
        </div>
        
        <div>
            <input class="btnCreate" type="submit" value="Create">
        </div>
    </fieldset>
</form>