<form  method="POST">
    <fieldset>
        <legend>Modify Room</legend>
        
        <div class="field">
            <label for="modify-room">Room name : </label>
            <div class="modify-room"><input type="text" id="modify-room" name="modify-room"></div>
        </div>
        
        <div class="field">
            <label for="modify-desc-room">Description : </label>
            <div class="modify-desc-room"><input type="text" id="modify-desc-room" name="modify-desc-room"></div>
        </div>
        
        
        <div>
            <input class="btnModify" type="submit" value="Modify">
        </div>
    </fieldset>
</form>